/*
✍️ תרגיל 1: שאילתות SELECT
1 הצג את כל התלמידים בטבלה
2 הצג רק את השם והציון של כל תלמיד
3 הצג את ממוצע הציונים
4 מצא את שנת הלידה הכי מוקדמת
*/

CREATE TABLE STUDENTS (
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  GRADE INTEGER,
  CLASS TEXT,
  BIRTHYEAR INTEGER
);

INSERT INTO STUDENTS (ID, NAME, GRADE, `CLASS`, BIRTHYEAR) VALUES (1, 'Liam', 95, 'H1', 2010);
INSERT INTO STUDENTS (ID, NAME, GRADE, `CLASS`, BIRTHYEAR) VALUES (2, 'Emma', 88, 'H2', 2011);
INSERT INTO STUDENTS (ID, NAME, GRADE, `CLASS`, BIRTHYEAR) VALUES (3, 'Noah', 76, 'W1', 2009);
INSERT INTO STUDENTS (ID, NAME, GRADE, `CLASS`, BIRTHYEAR) VALUES (4, 'Olivia', 83, 'W2', 2008);
INSERT INTO STUDENTS (ID, NAME, GRADE, `CLASS`, BIRTHYEAR) VALUES (5, 'Ava', 91, 'H1', 2010);
INSERT INTO STUDENTS (ID, NAME, GRADE, `CLASS`, BIRTHYEAR) VALUES (6, 'Ethan', 67, 'Z1', 2007);
INSERT INTO STUDENTS (ID, NAME, GRADE, `CLASS`, BIRTHYEAR) VALUES (7, 'Mia', 72, 'W1', 2009);
INSERT INTO STUDENTS (ID, NAME, GRADE, `CLASS`, BIRTHYEAR) VALUES (8, 'Tom', 55, 'H2', 2012);
INSERT INTO STUDENTS (ID, NAME, GRADE, `CLASS`, BIRTHYEAR) VALUES (9, 'Dana', 89, 'W2', 2010);
INSERT INTO STUDENTS (ID, NAME, GRADE, `CLASS`, BIRTHYEAR) VALUES (10, 'Isaac', 78, 'Z1', 2006);

--1
select *
from students

--2
select name , grade
from students

--3
select avg(grade)
from students
